### ISSUE TITLE
plugin-sh: Ignored unknown option

### ISSUE THREAD

**Issue by Luke-zhang-04** [rx-ts/prettier#106]
I keep getting `Ignored unknown option` when I run prettier. My shell files are still being formatted, so I have the extension installed.

![image](https://user-images.githubusercontent.com/55749227/118399642-20339600-b62c-11eb-893e-203d56a0d56c.png)

My config file:
```yaml
...

keepComments: true
indent: 4
binaryNextLine: true
switchCaseIndent: true
spaceRedirects: true
keepPadding: false
minify: false
functionNextLine: true

...
```
